---
argument_specs:
  main:
    short_description: "Configure and deploy sharded cluster"
    options:
      mongodb_sharding_setup_host:
        description: Target host address
        type: str
        required: true
      mongodb_sharding_setup_username:
        description: Authentication username
        type: str
      mongodb_sharding_setup_password:
        description: Authentication password
        type: str
        no_log: true
      mongodb_sharding_setup_api_key:
        description: API key for authentication
        type: str
        no_log: true
      mongodb_sharding_setup_validate_certs:
        description: Validate SSL certificates
        type: bool
        default: true
      mongodb_sharding_setup_state:
        description: Desired state
        type: str
        default: present
        choices: [present, absent]
